

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import qrcode
from qrcode.constants import ERROR_CORRECT_H, ERROR_CORRECT_L


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(457, 454)
        self.url = QtWidgets.QLineEdit(Form)
        self.url.setGeometry(QtCore.QRect(10, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.url.setFont(font)
        self.url.setObjectName("url")
        self.boxsize = QtWidgets.QLineEdit(Form)
        self.boxsize.setGeometry(QtCore.QRect(10, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boxsize.setFont(font)
        self.boxsize.setObjectName("boxsize")
        self.border = QtWidgets.QLineEdit(Form)
        self.border.setGeometry(QtCore.QRect(10, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.border.setFont(font)
        self.border.setObjectName("border")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 170, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fillcolor = QtWidgets.QLineEdit(Form)
        self.fillcolor.setGeometry(QtCore.QRect(120, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fillcolor.setFont(font)
        self.fillcolor.setObjectName("fillcolor")
        self.backcolor = QtWidgets.QLineEdit(Form)
        self.backcolor.setGeometry(QtCore.QRect(130, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.backcolor.setFont(font)
        self.backcolor.setObjectName("backcolor")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(10, 280, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(210, 270, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.type = QtWidgets.QComboBox(Form)
        self.type.setGeometry(QtCore.QRect(270, 290, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.type.setFont(font)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 340, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 420, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton.clicked.connect(self.create)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QR-CODE-GENERATER"))
        Form.setWindowIcon(QtGui.QIcon("download.png"))
        self.url.setToolTip(_translate("Form", "data"))
        self.url.setPlaceholderText(_translate("Form", "ENTER THE DATA"))
        self.boxsize.setToolTip(_translate("Form", "Box-Size"))
        self.boxsize.setPlaceholderText(_translate("Form", "Box-Size"))
        self.border.setToolTip(_translate("Form", "Border"))
        self.border.setPlaceholderText(_translate("Form", "Border"))
        self.label.setText(_translate("Form", "Fill-Color:"))
        self.label_2.setText(_translate("Form", "Back-Color:"))
        self.fillcolor.setPlaceholderText(_translate("Form", "Enter Color"))
        self.backcolor.setPlaceholderText(_translate("Form", "Enter Color"))
        self.name.setToolTip(_translate("Form", "name"))
        self.name.setPlaceholderText(_translate("Form", "Enter Name Of Image"))
        self.label_3.setText(_translate("Form", "Type:"))
        self.type.setItemText(0, _translate("Form", "png"))
        self.type.setItemText(1, _translate("Form", "jpg"))
        self.pushButton.setText(_translate("Form", "Generate Qrcode"))
        self.label_4.setText(_translate("Form", "Copyrights © abdallah kharoby"))
    


    def create(self):
        #inputs
        url=self.url.text()
        boxsize=self.boxsize.text()
        border=self.border.text()
        fillcolor=self.fillcolor.text()
        backcolor=self.backcolor.text()
        name=self.name.text()
        type=self.type.currentText()
        if(url == ""):
            msg=QMessageBox()
            msg.setWindowTitle("QrCodeGenerator")
            msg.setText("Don't Forget the input...")
            msg.setIcon(QMessageBox.Warning)
            x=msg.exec_()
        else:
                #qrcode maker
                qr = qrcode.QRCode(version=1,
                                   error_correction=qrcode.constants.ERROR_CORRECT_L, 
                                   box_size=boxsize,
                                   border=border)
        qr.add_data(url)
        qr.make(fit=True)
        img =qr.make_image(fill_color=fillcolor,back_color=backcolor)
        img.save(name + "." + type)
        #message box
        msg= QMessageBox()
        msg.setWindowTitle("QrCodeGenerator")
        msg.setText("QrCode has been created!!")
        msg.setIcon(QMessageBox.Information)
        x=msg.exec_()
        #clear inputs
        self.url.clear()
        self.boxsize.clear()
        self.border.clear()
        self.fillcolor.clear()
        self.backcolor.clear()
        self.name.clear()
            






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
